In [1]:
import numpy as np

data = np.array([
    ("Wings of Fire", "A.P.J. Abdul Kalam", 250.0),
    ("Harry Potter", "J.K. Rowling", 400.0),
    ("The Alchemist", "Paulo Coelho", 300.0),
    ("Atomic Habits", "James Clear", 500.0)
], dtype=[("title", "U30"), ("author", "U20"), ("price", "f4")])

print(data)

[('Wings of Fire', 'A.P.J. Abdul Kalam', 250.)
 ('Harry Potter', 'J.K. Rowling', 400.)
 ('The Alchemist', 'Paulo Coelho', 300.)
 ('Atomic Habits', 'James Clear', 500.)]


In [2]:
print(data["title"])

['Wings of Fire' 'Harry Potter' 'The Alchemist' 'Atomic Habits']


In [3]:
print(data[1])

('Harry Potter', 'J.K. Rowling', 400.)


In [4]:
amount = 350

print(data["title"][data["price"] < amount])

['Wings of Fire' 'The Alchemist']


In [5]:
import numpy as np

dtype1 = {
    "names": ["title", "author", "price"],
    "formats": ["U30", "U20", "f4"]
}

dtype1 = np.dtype(dtype1)

print(dtype1)

[('title', '<U30'), ('author', '<U20'), ('price', '<f4')]


In [6]:
dtype2 = np.dtype([
    ("title", "U30"),
    ("author", "U20"),
    ("price", "f4")
])

print(dtype2)

[('title', '<U30'), ('author', '<U20'), ('price', '<f4')]


In [7]:
print(dtype1 == dtype2)

True


In [8]:
import numpy as np

data_rec = data.view(np.recarray)

print(data_rec.price)

[250. 400. 300. 500.]


In [9]:
data["price"]

array([250., 400., 300., 500.], dtype=float32)

In [10]:
data_rec.price

array([250., 400., 300., 500.], dtype=float32)

In [11]:
import numpy as np

students = np.array([
    (1, "Rahul", 75.5),
    (2, "Anu", 89.0),
    (3, "Kiran", 68.5),
    (4, "Sneha", 95.0),
    (5, "Arjun", 82.0)
], dtype=[
    ("roll_no", "i4"),
    ("name", "U20"),
    ("marks", "f4")
])

students = np.sort(students, order="marks")[::-1]

print(students)

[(4, 'Sneha', 95. ) (2, 'Anu', 89. ) (5, 'Arjun', 82. ) (1, 'Rahul', 75.5)
 (3, 'Kiran', 68.5)]
