In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
import numpy as z
arr=z.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
arr=np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


In [4]:
import numpy as np
array=np.ones((3,2),dtype=int)
print(array)

[[1 1]
 [1 1]
 [1 1]]


In [5]:
import numpy as np
arr=np.array([2,3,4],dtype=float)
print(arr,type(arr))

[2. 3. 4.] <class 'numpy.ndarray'>


In [10]:
import numpy as b
arr=b.empty((2,2))
print(arr)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.25154373e-311]]


In [7]:
import numpy as n
x=n.arange(0,20,2)
print(x)

[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
import numpy as np
ar=np.linspace(0,1,6)
print(ar)

[0.  0.2 0.4 0.6 0.8 1. ]


In [9]:
np.random.random((3,3))

array([[0.13755243, 0.42426105, 0.66171272],
       [0.02655069, 0.29286641, 0.54902011],
       [0.73286014, 0.03043154, 0.9174819 ]])