In [4]:
import numpy as np
a = np.arange(1, 21)

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
20
<class 'numpy.ndarray'>


In [5]:
import numpy as np

np.random.seed(0)
arr = np.random.randint(0, 51, size=(4, 5))
print(arr)
print(arr.itemsize)
print(arr.nbytes)

[[44 47  0  3  3]
 [39  9 19 21 50]
 [36 23  6 24 24]
 [12  1 38 39 23]]
4
80


In [6]:
import numpy as x

arr = x.arange(1, 13).reshape(3, 4)
print(arr)
print(arr[1, 2])
print(arr[-1])
print(arr[:, -1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[ 9 10 11 12]
[ 4  8 12]


In [7]:
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print(arr[:2, :2])
print(arr[:, ::2])
print(arr[:, ::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [8]:
import numpy as np

arr = np.arange(1, 21).reshape(4, 5)
print(arr)
view = arr[:3, :4]
view[0, 0] = 100
print(view)
print(arr)
copy_arr = arr[:3, :4].copy()
copy_arr[0, 0] = 200
print(copy_arr)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[100   2   3   4]
 [  6   7   8   9]
 [ 11  12  13  14]]
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]
[[200   2   3   4]
 [  6   7   8   9]
 [ 11  12  13  14]]
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [9]:
import numpy as np
x = np.arange(1, 13)
print(x)
matrix = x.reshape(3, 4)
print(matrix)
col1 = x.reshape(12, 1)
print(col1)
col2 = x[:, np.newaxis]
print(col2)
print(np.array_equal(col1, col2))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
True


In [10]:
import numpy as np

np.random.seed(0)
a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (2, 3))
print(a)
print(b)
v1 = np.vstack((a, b))
v2 = np.concatenate((a, b), axis=0)
print(v1)
print(v2)
print(np.array_equal(v1, v2))
h1 = np.hstack((a, b))
h2 = np.concatenate((a, b), axis=1)
print(h1)
print(h2)
print(np.array_equal(h1, h2))

[[6 1 4]
 [4 8 4]]
[[6 3 5]
 [8 7 9]]
[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]]
[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]]
True
[[6 1 4 6 3 5]
 [4 8 4 8 7 9]]
[[6 1 4 6 3 5]
 [4 8 4 8 7 9]]
True


In [11]:
import numpy as np
arr = np.arange(1, 16)
print(arr)
part = np.split(arr, 3)
print(part[0])
print(part[1])
print(part[2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [12]:
import numpy as np
arr = np.arange(1, 25).reshape(6, 4)
print(arr)
h = np.hsplit(arr, 2)
print(h[0])
print(h[1])
v = np.vsplit(arr, 2)
print(v[0])
print(v[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]
 [23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
